spring.application.name=SubastaYa-Proyecto_Software
spring.datasource.url=jdbc:postgresql://localhost:5432/subastaya

spring.datasource.username=postgres
spring.datasource.password=2026

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.proprerties.hibernate.show_sql=true
