spring.application.name=subastaYa-PS
spring.datasource.url=jdbc:postgresql://localhost:5432/subastaya_db

spring.datasource.username=postgres
spring.datasource.password=morena09

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
#Muestra las consultas SQL que ejecuta Hibernate en la consola
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true