create table auctions (
                          base_price numeric(38,2) not null,
                          minimum_increment numeric(38,2) not null,
                          version integer not null,
                          buyer_id bigint not null,
                          category_id bigint not null,
                          end_date timestamp(6) not null,
                          id bigint generated by default as identity,
                          start_date timestamp(6) not null,
                          description TEXT,
                          image_url varchar(255),
                          state varchar(255) not null,
                          title varchar(255) not null,
                          primary key (id)
);

create table audit_logs (
                            date timestamp(6) not null,
                            entity_id bigint not null,
                            id bigint generated by default as identity,
                            user_id bigint,
                            action varchar(255) not null,
                            detalle_json TEXT,
                            entity varchar(255) not null,
                            primary key (id)
);

create table bids (
                      amount numeric(38,2) not null,
                      auction_id bigint not null,
                      bid_date timestamp(6) not null,
                      bidder_id bigint not null,
                      id bigint generated by default as identity,
                      primary key (id)
);

create table categories (
                            id bigint generated by default as identity,
                            description varchar(255) not null,
                            name varchar(255) not null unique,
                            primary key (id)
);

create table ledger_transactions (
                                     amount numeric(38,2) not null,
                                     auction_id bigint,
                                     date timestamp(6) not null,
                                     id bigint generated by default as identity,
                                     wallet_id bigint not null,
                                     type varchar(255) not null,
                                     primary key (id)
);

create table users (
                       id bigint generated by default as identity,
                       registration_date timestamp(6) not null,
                       email varchar(255) not null unique,
                       name varchar(255) not null,
                       password_hash varchar(255) not null,
                       primary key (id)
);

create table wallets (
                         available_balance numeric(38,2) not null,
                         retained_balance numeric(38,2) not null,
                         total_balance numeric(38,2) not null,
                         version integer not null,
                         id bigint generated by default as identity,
                         users_id bigint not null unique,
                         primary key (id)
);

alter table auctions
    add constraint FK5fs9h9t6kpm27f4855cp0tdxc
        foreign key (buyer_id)
            references users;

alter table auctions
    add constraint FK1rnccdrsds9uu13sm6domfns9
        foreign key (category_id)
            references categories;

alter table bids
    add constraint FKbm89m2gow82dotpnlcp7t3p5f
        foreign key (auction_id)
            references auctions;

alter table bids
    add constraint FKmtrc6tnwawlpk1u2km6qnxbha
        foreign key (bidder_id)
            references users;

alter table ledger_transactions
    add constraint FKfjlxhqk5jse0wd25dlgtfsc6p
        foreign key (wallet_id)
            references wallets;

alter table wallets
    add constraint FK7x94fwrogfbq11p4wg5dhd0m
        foreign key (users_id)
            references users;